"""Text ingestion: pull plain text out of .txt/.docx/.pdf bytes and normalise it."""

import io
import re
from pathlib import Path

import docx
import pdfplumber

# Matches artefact lines printers add, e.g. "Page 2 of 5"; they carry no legal meaning.
PAGE_LINE_RE = re.compile(r"^\s*Page \d+( of \d+)?\s*$", re.IGNORECASE)
# "List Number 2" -> 2; Word's built-in list styles encode their depth in the name.
STYLE_LEVEL_RE = re.compile(r"(\d+)\s*$")


def _list_format(numbering, num_id: int, ilvl: int) -> str | None:
    """Look up a list level's w:numFmt ("decimal", "bullet", ...) in numbering.xml."""
    if numbering is None:
        return None
    abstract_ids = numbering.xpath(f'./w:num[@w:numId="{num_id}"]/w:abstractNumId/@w:val')
    if not abstract_ids:
        return None
    formats = numbering.xpath(
        f'./w:abstractNum[@w:abstractNumId="{abstract_ids[0]}"]'
        f'/w:lvl[@w:ilvl="{ilvl}"]/w:numFmt/@w:val'
    )
    return formats[0] if formats else None


def _numbering_of(paragraph, numbering) -> tuple[int, int] | None:
    """Return (numId, level) for an auto-numbered decimal paragraph, else None.

    The number may be set on the paragraph itself (w:numPr) or inherited from
    its style ("List Number"). Bullet lists also use w:numPr, so the list's
    format is looked up and bullets are ignored.
    """
    pPr = paragraph._p.pPr
    num_pr = pPr.numPr if pPr is not None else None
    from_style = False
    if num_pr is None:
        style_pPr = paragraph.style.element.pPr if paragraph.style is not None else None
        num_pr = style_pPr.numPr if style_pPr is not None else None
        from_style = True
    if num_pr is None or num_pr.numId is None or num_pr.numId.val == 0:
        return None  # numId 0 is Word's way of switching numbering off
    num_id = num_pr.numId.val
    ilvl = num_pr.ilvl.val if num_pr.ilvl is not None else 0
    if _list_format(numbering, num_id, ilvl) in ("bullet", "none"):
        return None
    level = ilvl
    if from_style and num_pr.ilvl is None:
        # Built-in list styles are one-level lists; "List Number 2" is the
        # second outline level, so take the depth from the style name.
        match = STYLE_LEVEL_RE.search(paragraph.style.name or "")
        level = int(match.group(1)) - 1 if match else 0
    return num_id, level


def _docx_paragraph_texts(document) -> list[str]:
    """Paragraph texts with Word's automatic numbers put back in front.

    python-docx drops numbers generated by Word numbering, so "1. Definitions"
    arrives as "Definitions" and the segmenter cannot see the clause start.
    This is a best-effort rebuild, not a copy of Word's numbering engine:
    level 0 gives "1.", "2."; level 1 gives "1.1", "1.2" (parent number plus
    child counter); deeper levels give "(a)", "(b)". Custom formats, start
    values and restarts defined in numbering.xml are ignored.
    """
    try:
        numbering = document.part.numbering_part.element
    except NotImplementedError:
        numbering = None  # document has no numbering part at all
    counters = {}  # (numId, level) -> last number used
    last_top = 0  # most recent level 0 number, the parent of level 1 items
    texts = []
    for paragraph in document.paragraphs:
        info = _numbering_of(paragraph, numbering)
        if info is None or not paragraph.text.strip():
            texts.append(paragraph.text)
            continue
        num_id, level = info
        counters[(num_id, level)] = counters.get((num_id, level), 0) + 1
        # A shallower item starting means every deeper list restarts at 1.
        # This is document-wide because Word's list styles use a separate
        # numId per level ("List Number" and "List Number 2" differ).
        for key in [k for k in counters if k[1] > level]:
            del counters[key]
        count = counters[(num_id, level)]
        if level == 0:
            last_top = count
            prefix = f"{count}."
        elif level == 1:
            prefix = f"{last_top}.{count}"
        else:
            # (a) to (z); past 26 items fall back to the number itself.
            prefix = f"({chr(ord('a') + count - 1)})" if count <= 26 else f"({count})"
        texts.append(f"{prefix} {paragraph.text}")
    return texts


def extract_text(data: bytes, filename: str) -> str:
    """Extract plain text from file bytes, dispatching on the lower-cased extension."""
    ext = Path(filename).suffix.lower()
    if ext == ".txt":
        try:
            raw = data.decode("utf-8")
        except UnicodeDecodeError:
            # Windows-authored files are often cp1252; fall back rather than fail.
            raw = data.decode("cp1252")
    elif ext == ".docx":
        document = docx.Document(io.BytesIO(data))
        parts = _docx_paragraph_texts(document)
        # Tables live outside the paragraph stream, so collect cell text separately.
        for table in document.tables:
            for row in table.rows:
                for cell in row.cells:
                    parts.append(cell.text)
        raw = "\n".join(parts)
    elif ext == ".pdf":
        with pdfplumber.open(io.BytesIO(data)) as pdf:
            raw = "\n".join(page.extract_text() or "" for page in pdf.pages)
    else:
        raise ValueError(f"Unsupported file type: {ext}")
    return clean_text(raw)


def clean_text(text: str) -> str:
    """Normalise extracted text while keeping its line structure intact."""
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    # Word processors emit curly quotes/dashes; downstream matchers expect ASCII.
    text = text.replace("\u2018", "'").replace("\u2019", "'")
    text = text.replace("\u201c", '"').replace("\u201d", '"')
    text = text.replace("\u2014", "-").replace("\u2013", "-")
    text = text.replace("\u00a0", " ")
    text = "\n".join(line for line in text.split("\n") if not PAGE_LINE_RE.match(line))
    # PDF/Word wrap long words with a hyphen at the line break; rejoin them.
    text = re.sub(r"(\w)-\n(\w)", r"\1\2", text)
    text = "\n".join(line.rstrip() for line in text.split("\n"))
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()
